[project]
name = "reporting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "prometheus-api-client>=0.7.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
